// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Domain.Models;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;

namespace Domain.Models
{
    public partial interface IExamsContextProcedures
    {
        Task<List<USP_Query_CustomerResult>> USP_Query_CustomerAsync(string name, string status, int? Skip, int? Take, string SortBy, string SortDirection, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
