// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Models
{
    public partial class Menu
    {
        public Menu()
        {
            UserMenu = new HashSet<UserMenu>();
        }

        public int MenuId { get; set; }
        public string MenuName { get; set; }
        public string MenuUrl { get; set; }

        public virtual ICollection<UserMenu> UserMenu { get; set; }
    }
}